// macOS confirmation dialog shown by Turnweft itself (U11 channel when the host declines MCP elicitation).
// Run by the detached `turnweft dialog <proposalId>` helper (U19), so it can wait as long as the user needs.
// The text is generated by core and passed to osascript as an argument (no string interpolation into the
// script). The model never sees or answers this dialog. "Deny" is the default and the cancel button; only an
// explicit "Allow" click within the timeout counts. Any error, timeout or non-macOS platform returns false.
import { currentLanguage, text, type Language } from "../core/i18n.js";
import { execFile, spawn } from "node:child_process";
import type { PolicyProposal } from "../core/types.js";

export type NativeConfirm = (proposal: PolicyProposal, timeoutMs: number, signal?: AbortSignal, onSpawn?: (pid: number) => void) => Promise<{ accepted: boolean; detail: string }>;

const SCRIPT = [
  "on run argv",
  "set msg to item 1 of argv",
  "set secs to (item 2 of argv) as integer",
  "set denyLabel to item 3 of argv",
  "set allowLabel to item 4 of argv",
  'display dialog msg with title "Turnweft" buttons {denyLabel, allowLabel} default button denyLabel cancel button denyLabel with icon caution giving up after secs',
  'return (button returned of result) & "|" & (gave up of result)',
  "end run",
];

export const macosConfirm: NativeConfirm = (proposal, timeoutMs, signal, onSpawn) => {
  if (process.platform !== "darwin" || process.env.TURNWEFT_NO_NATIVE_DIALOG === "1") {
    return Promise.resolve({ accepted: false, detail: "native dialog unavailable on this platform or disabled" });
  }
  const secs = Math.max(5, Math.floor(timeoutMs / 1000));
  // U19: the dialog waits for the user; it only closes when the proposal itself expires (shown as a fixed date).
  const language = currentLanguage();
  const expires = new Date(proposal.expiresAt).toLocaleString(language === "zh" ? "zh-CN" : "en-US", { hour12: false });
  const message = `${proposal.message}\n\n${text("dialog", { id: proposal.proposalId, expires }, language)}`;
  const args = SCRIPT.flatMap((line) => ["-e", line]).concat([message, String(secs), text("deny", undefined, language), text("allow", undefined, language)]);
  return new Promise((resolve) => {
    // The signal closes the dialog when the proposal is decided elsewhere (e.g. in a terminal) (round 5, 8).
    const child = execFile("osascript", args, { timeout: timeoutMs + 5000, signal }, (err, stdout, stderr) => {
      if (signal?.aborted) return resolve({ accepted: false, detail: "closed: decided elsewhere" });
      if (err) {
        // Pressing the cancel button exits with -128 (User canceled).
        const canceled = /-128|User canceled/i.test(String(stderr) + String(err.message));
        return resolve({ accepted: false, detail: canceled ? "denied in dialog" : `dialog error: ${String(stderr || err.message).trim().slice(0, 160)}` });
      }
      const [button, gaveUp] = String(stdout).trim().split("|");
      resolve({ accepted: dialogAccepted(String(stdout), language), detail: gaveUp === "true" ? "dialog timed out" : `button ${button}` });
    });
    if (child.pid) onSpawn?.(child.pid);
  });
};

/** Start the detached dialog helper for a proposal (macOS only; disabled by TURNWEFT_NO_NATIVE_DIALOG=1). */
export function spawnDialogHelper(proposalId: string, cliMain: string) {
  if (process.platform !== "darwin" || process.env.TURNWEFT_NO_NATIVE_DIALOG === "1") return false;
  const child = spawn(process.execPath, [cliMain, "dialog", proposalId], { detached: true, stdio: "ignore", env: process.env });
  child.on("error", () => { /* the terminal grant remains available */ });
  child.unref();
  return true;
}

export function dialogAccepted(stdout: string, language: Language): boolean {
  const [button, gaveUp] = stdout.trim().split("|");
  return button === text("allow", undefined, language) && gaveUp === "false";
}
