// TurnweftService: the only API the host layer (mcp/, cli/) may call.
// Implemented by core (runtime/). Host code must not touch the store, workers or adapters directly.
import type {
  HostBinding, Intent, Job, JobResult, PolicyProposal, ProbeResult, ProviderId,
  Session, TurnEvent, UserPolicy,
} from "./types.js";

export interface CreateSessionInput {
  provider: ProviderId;
  /** Any path inside the project; core canonicalizes it (realpath, symlink-escape checks). */
  cwd: string;
  name?: string;
  /** Explicit model request. Omit to use the provider's own configuration (product default). */
  model?: string;
  host: HostBinding;
}

export interface SubmitTurnInput {
  sessionId: string;
  intent: Intent;
  prompt: string;
  /** Generated by the caller BEFORE submitting; resubmitting the same id returns the same job (§8.5). */
  requestId: string;
  host: HostBinding;
}

/**
 * Result of submitting a turn.
 * - "accepted": job recorded durably; poll with getJob.
 * - "awaiting_confirmation" (U19): a U11 policy is missing. The job is recorded in state
 *   waiting_confirmation and starts by itself once the human confirms (MCP elicitation, the macOS dialog,
 *   or `turnweft policy grant`). No resubmit is needed. A denial cancels it; it never times out into a
 *   denial, only expires with the proposal. Nothing runs before confirmation.
 * - "needs_confirmation": legacy shape (nothing recorded); core no longer returns it.
 * - "rejected": e.g. capability_mismatch, invalid cwd, session closed.
 */
export type SubmitTurnOutcome =
  | { kind: "accepted"; job: Job }
  | { kind: "awaiting_confirmation"; job: Job; proposal: PolicyProposal }
  | { kind: "needs_confirmation"; proposal: PolicyProposal }
  | { kind: "rejected"; code: string; message: string };

export interface GetJobInput {
  jobId: string;
  /** Return events after this sequence number. */
  afterSeq?: number;
  /** Bounded wait for a state change, in ms. Core clamps it below the host tool timeout. */
  waitMs?: number;
  /** Include the (paged) result when terminal. */
  includeResult?: boolean;
  resultOffset?: number;
  resultLimit?: number;
}

export interface JobView {
  job: Job;
  session: Pick<Session, "id" | "provider" | "state" | "cwd" | "canonicalRoot">;
  terminal: boolean;
  events: TurnEvent[];
  nextSeq: number;
  /** Suggested next step for the calling agent. */
  nextAction: "wait" | "read_result" | "confirm_policy" | "reconcile_in_doubt" | "none";
  result?: JobResult;
  resultNextOffset?: number;
}

export interface ConfirmPolicyInput {
  proposalId: string;
  nonce: string;
  /** Who confirmed: an MCP elicitation accept, the macOS dialog shown by Turnweft itself, or `policy grant` on a TTY. */
  via: "elicitation" | "native-dialog" | "cli-tty";
}

export interface TurnweftService {
  listAgents(opts?: { refresh?: boolean }): Promise<ProbeResult[]>;

  createSession(input: CreateSessionInput): Promise<Session>;
  listSessions(filter: { canonicalRoot?: string; provider?: ProviderId; host?: HostBinding; includeClosed?: boolean }): Promise<Session[]>;
  getSession(sessionId: string): Promise<Session | undefined>;
  /** Explicit cross-host attach (§8.2). Verifies project and owner state. */
  attachSession(sessionId: string, host: HostBinding): Promise<Session>;
  /** Default policy "reject_if_busy"; "cancel_running" cancels the running turn first. */
  closeSession(sessionId: string, policy?: "reject_if_busy" | "cancel_running"): Promise<Session>;

  submitTurn(input: SubmitTurnInput): Promise<SubmitTurnOutcome>;
  getJob(input: GetJobInput): Promise<JobView>;
  /** Idempotent. Confirms "cancelled" only after the provider is observed to stop. */
  cancelJob(jobId: string): Promise<Job>;

  /** Confirms the proposal; jobs waiting on it (or on a pending proposal with the same key) are released. */
  confirmPolicy(input: ConfirmPolicyInput): Promise<UserPolicy>;
  /** The human explicitly denied: the proposal is consumed and jobs waiting on it are cancelled. */
  rejectPolicy(input: ConfirmPolicyInput): Promise<void>;
  listPolicies(filter?: { canonicalRoot?: string; provider?: ProviderId }): Promise<UserPolicy[]>;
  revokePolicy(policyId: string): Promise<UserPolicy>;
  /** Proposal lookup for `turnweft policy grant <proposalId>` in a real TTY (includes `decision` once decided). */
  getProposal(proposalId: string): Promise<PolicyProposal | undefined>;
  /** One dialog helper per proposal: claim with a pid+start-time token; false if a live helper owns it or it is decided. */
  claimConfirmationDialog(proposalId: string, ownerToken: string): Promise<boolean>;
  releaseConfirmationDialog(proposalId: string, ownerToken: string): Promise<void>;
  /** The helper records its dialog child, so a successor can close a dialog left behind by a killed helper. */
  recordConfirmationDialogChild(proposalId: string, ownerToken: string, childPid: number): Promise<void>;
}
