// Turnweft core contracts. Design references: TURNWEFT_DESIGN_AND_DEVELOPMENT_PLAN.md §7–§10.
// These types are the boundary between the host layer (mcp/, cli/) and the core (runtime/, adapters/).

export type ProviderId = "dim" | "droid" | "grok" | "opencode" | "agy";
export const PROVIDERS: readonly ProviderId[] = ["dim", "droid", "grok", "opencode", "agy"];

export type HostKind = "claude-code" | "codex" | "cli";

/** §7.1: what this turn is for. Never inferred from tool names like "review". */
export type Intent = "analyze" | "implement";

/** §7.1: where the agent works. Only "direct" is implemented in the first version. */
export type WorkspaceMode = "direct";

// ---------------------------------------------------------------- capabilities (§8.3)

export type Transport = "acp" | "native-stream";

export interface AgentCapabilities {
  transport: Transport;
  multiTurn: boolean;
  resumeAfterRestart: "supported" | "unsupported" | "unverified";
  cancelTurn: "protocol" | "process" | "unsupported";
  /** callback: per-request approvals answered by Turnweft; native-policy: rules/tiers set at launch. */
  permissions: "callback" | "native-policy" | "coarse" | "unverified";
  structuredEvents: "exact" | "inferred" | "none";
  modelConfig: "session" | "launch" | "provider-default";
  /** How a thinking level (U23) is applied: an ACP thought_level option, a launch flag, or not at all. */
  effortConfig: "session" | "launch" | "unsupported";
}

export interface ProbeResult {
  provider: ProviderId;
  available: boolean;
  executable?: string;
  cliVersion?: string;
  adapterVersion: string;
  capabilities?: AgentCapabilities;
  /** Human-readable problems, e.g. "not logged in", "binary not found". */
  problems: string[];
  probedAt: string;
}

// ---------------------------------------------------------------- policy (§7.3, §7.4, U11)

export interface WorkspaceGrant {
  id: string;
  canonicalRoot: string;
  issuer: "host" | "user-policy" | "explicit-task";
  operations: {
    read: boolean;
    write: boolean;
    execute: "none" | "task-scoped";
    network: "denied" | "host-policy";
  };
  revision: number;
}

/** A U11 record: the user accepted a specific native tier for provider × project × intent. */
export interface UserPolicy {
  id: string;
  provider: ProviderId;
  canonicalRoot: string;
  intent: Intent;
  /** Provider-native tier, e.g. "workspace-write", "auto-medium", "accept-edits+allow:command(npm)". */
  tier: string;
  /** Operations this tier allows beyond the grant, as shown to the user at confirmation time. */
  excessOverGrant: string[];
  cliVersion: string;
  adapterVersion: string;
  capabilityDigest: string;
  confirmedVia: "elicitation" | "native-dialog" | "cli-tty";
  confirmedAt: string;
  revision: number;
  revokedAt?: string;
  expiresAt?: string;
}

/** Shown to the human before a UserPolicy is written. Generated by core, never by the model. */
export interface PolicyProposal {
  proposalId: string;
  nonce: string;
  provider: ProviderId;
  canonicalRoot: string;
  intent: Intent;
  tier: string;
  excessOverGrant: string[];
  cliVersion: string;
  adapterVersion: string;
  capabilityDigest: string;
  /** Plain-language message for the confirmation UI. */
  message: string;
  expiresAt: string;
  /** Set once decided; a decided proposal can no longer be confirmed or rejected. */
  decision?: "confirmed" | "rejected" | "expired" | "merged";
  /** Jobs still waiting on this proposal's key (filled on lookup); 0 means the dialog is no longer needed. */
  waitingJobs?: number;
}

// ---------------------------------------------------------------- identities (§8.1, §8.2)

export interface HostBinding {
  hostKind: HostKind;
  /** Stable host conversation id, e.g. Codex `x-codex-turn-metadata.thread_id`. */
  conversationId?: string;
  /** Fallback when the host gives no stable id: the MCP connection registration id. */
  connectionId?: string;
}

export type SessionState = "opening" | "ready" | "busy" | "suspended" | "recovering" | "broken" | "closed";

export interface Session {
  id: string; // tws_...
  provider: ProviderId;
  name?: string;
  /** Directory the agent works in: exactly what the caller asked for (realpath). */
  cwd: string;
  /** Project root (git top-level, else cwd). Scopes write locks and U11 policies, never the agent's cwd. */
  canonicalRoot: string;
  nativeSessionId?: string;
  state: SessionState;
  brokenReason?: string;
  hostBindings: HostBinding[];
  capabilities?: AgentCapabilities;
  cliVersion?: string;
  /** Model explicitly requested for this session (never a product default; U12). */
  requestedModel?: string;
  /** Thinking level explicitly requested for this session, in the provider's own values (U23; never a product default). */
  requestedEffort?: string;
  createdAt: string;
  updatedAt: string;
}

export type JobState =
  /** U19: accepted but held until the user confirms the U11 proposal (no timeout-deny; expires after the proposal TTL). */
  | "waiting_confirmation"
  | "queued" | "starting" | "running" | "waiting_permission" | "cancel_requested"
  | "succeeded" | "failed" | "cancelled" | "timed_out" | "in_doubt";

export const TERMINAL_JOB_STATES: readonly JobState[] = ["succeeded", "failed", "cancelled", "timed_out", "in_doubt"];

export interface Job {
  confirmationMode?: "wait" | "fail-fast";
  id: string; // twj_...
  sessionId: string;
  requestId: string;
  intent: Intent;
  promptDigest: string;
  state: JobState;
  failureReason?: string;
  /** e.g. "auth_required", "capability_mismatch", "permission_blocked", "context_lost". */
  errorCode?: string;
  grantRevision?: number;
  policyId?: string;
  /** Set while the job waits for a U11 confirmation (state waiting_confirmation). */
  proposalId?: string;
  /** U21: authorized by the submitting host's bypass mode, independent of any stored U11 policy. */
  hostBypass?: string;
  /** Capability digest the bypass authorized; the worker runs on bypass only while it still matches (round 11, 5). */
  hostBypassDigest?: string;
  ownerGeneration?: number;
  acceptedAt: string;
  deliveredAt?: string;
  startedAt?: string;
  finishedAt?: string;
  /** U24: overlapping implement job IDs, retained even after owner-loss recovery. */
  concurrentWrites?: string[];
}

// ---------------------------------------------------------------- events (§10.4)

export type EventType =
  | "session.ready" | "turn.accepted" | "turn.started" | "text.delta"
  | "tool.started" | "tool.completed" | "permission.requested" | "permission.resolved"
  | "config.readback" | "turn.completed" | "turn.failed" | "diagnostic";

export interface TurnEvent {
  jobId: string;
  seq: number;
  type: EventType;
  at: string;
  source: "turnweft" | ProviderId;
  payload: Record<string, unknown>;
  truncated?: boolean;
}

// ---------------------------------------------------------------- results (§10.3)

export interface PermissionMapping {
  /** What the native side actually ran with, read back after open/resume (§7.4). */
  effectiveMode: string;
  grantRevision?: number;
  policyId?: string;
  /** U21: set when the host's bypass mode, not a stored policy, authorized the excess. */
  authorizedBy?: string;
  excessOverGrant: string[];
  /** Approvals Turnweft answered on the provider's behalf during this turn. */
  answeredRequests: Array<{ kind: string; title: string; decision: "allow" | "deny" }>;
}

export interface FileChangeEvidence {
  method: "git" | "snapshot" | "none";
  /** Paths inside the session's cwd changed during this turn, excluding paths already dirty before it. */
  changed: string[];
  /**
   * Paths elsewhere in the repository that changed during the turn. They may be the agent's, or concurrent
   * edits by the user or another session (live CC test); never attribute them without checking.
   */
  changedOutsideCwd?: string[];
  preexistingDirty: string[];
}

export interface JobResult {
  /** Other implement jobs that ran concurrently in this canonical root. */
  concurrentWrites?: string[];
  sessionId: string;
  jobId: string;
  provider: ProviderId;
  cliVersion?: string;
  adapterVersion: string;
  cwd: string;
  nativeSessionId?: string;
  state: JobState;
  stopReason?: string;
  finalText: string;
  resultComplete: boolean;
  truncated: boolean;
  permission?: PermissionMapping;
  model?: { requested?: string; effective?: string };
  /** U23: thinking level. `effective` is the provider's read-back; for launch-flag providers (agy) it is the flag passed. */
  effort?: { requested?: string; effective?: string };
  files?: FileChangeEvidence;
  toolCalls: Array<{ kind?: string; title?: string; status?: string }>;
}

/** Envelope for every host-facing call. `ok` = the request was processed, not that the job succeeded. */
export interface Envelope<T> {
  ok: boolean;
  data: T | null;
  error: { code: string; message: string; details?: Record<string, unknown> } | null;
  warnings: string[];
}
